export { useMentionParsing, extractMentions, renderMentionsInHtml, detectMentionContext, buildMentionText, getMentionDisplayName, getMentionSubtitle, getMentionProvider, getActiveMentionProviders, formatMentionsForApi, groupMentionsByType } from './useMentionParsing'
export { useChatMarkdown, type UseChatMarkdownReturn } from './useChatMarkdown'
export { useChatScroll, type UseChatScrollReturn } from './useChatScroll'
export { useChatErrorHandling, type UseChatErrorHandlingReturn } from './useChatErrorHandling'
export { useAiContext } from './useAiContext'
export { useAiSuggestions } from './useAiSuggestions'
export { usePageAiContext } from './usePageAiContext'
export { useKeyboardShortcut, useAiDrawerShortcut, type UseKeyboardShortcutOptions } from './useKeyboardShortcut'
export { useLoadingText } from './useLoadingText'
export { useHistoryLimit } from './useHistoryLimit'
export { useFileAttachments, useMentionInput, useInputSuggestions, useTextareaResize } from './useChatInput'
